### PR TITLE
Update client.rb

### PR DESCRIPTION
**Pull request by mzahed**
Option to customize the login url

### CODE REVIEW

**Comment by mzahed** [comment]
This is because the endpoint and login_url for enterprise is different than partners

**Comment by jheth** [comment]
@mzahed Sorry for the delay on this. Can you give an example of a enterprise login url?  We have the option for "host" to be defined and services/Soap/u/{version} gets appended.  Is the endpoint different?

**Comment by mzahed** [comment]
@jheth yea its https://login.salesforce.com/services/Soap/c/34.0/..., notice the c instead of the u. just need a way to customize that

**Comment by jheth** [comment]
Thanks @mzahed. I'll merge this for now. I may change it in the future though.

**Pull request merged**
